### ISSUE TITLE
TypeError: __deepcopy__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by omerfguzel** [h3ik0th/Darts_ensembleFC#1]
Hi,
I'm getting this error when I run the ensemble_eval function. Is there any fix suggestions?
**TypeError: __deepcopy__() takes 1 positional argument but 2 were given**

**Comment by h3ik0th** [comment]
Hi,
after some experimenting I found that the class RegressionEnsembleModel in Darts has apparently been modified. The argument "forecasting_models" no longer accepts the list "models" of instantiated models. 
Below, I commented out the syntax that worked in October and inserted a new line below. In argument "forecasting_models", I list the forecast methods explicitly, one by one. 

old:
    # ensemble_model = RegressionEnsembleModel(forecasting_models=models, regression_train_n_points=n_train)

new:
    ensemble_model = RegressionEnsembleModel(
                                forecasting_models=[ Theta(best_theta), Prophet(), AutoARIMA(), NaiveDrift() ], 
                                regression_train_n_points=12)

I still need to look if there is any workaround, so that RegressionEnsembleModel accepts instantiated forecast models. The Darts docu doesn't mention anything.

**Comment by h3ik0th** [comment]
Revised Juypter notebook uploaded: the new code line I mentioned above prevents the runtime error

**Comment by omerfguzel** [comment]
Thank you so much sir, solved my  problem.

**Comment by dennisbader** [comment]
@h3ik0th and @omerfguzel, thanks for that. We will improve the error message, see [Darts issue 724](https://github.com/unit8co/darts/issues/724).

When creating a model object all parameters are saved.
Deepcopying fitted/trained forecasting_models with EnsembleModels fails.

You can reset your models with models_untrained = [m.untrained_model() for m in models]
